[default]
extend-ignore-re = [
    # NOTE: use here for regex patterns
    "xpub.*",
    "xprv.*",
    "3.*", # address
    "5.*", # address
    "private_key .*",
    "privkey .*",
    "tt.*", # <tt> tags
    "code.*", # <code> tags
    "\\w*<sub>", # prefix for <sub> tags
    "OP_SUCCESSx|\\d+",
    "pay.*",
    "ser.*",
    "prefix.*",
    "value: .*",
]

[default.extend-words]
# NOTE: use here for false-positives
PSBT = "PSBT"
ser = "ser"
anc = "anc"
# Names
Atack = "Atack"
Ono = "Ono"
Meni = "Meni"

