name: GitHub Actions Check
run-name: ${{ github.actor }} Checks 🚀
on: [push, pull_request]
jobs:
  All-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: scripts/link-format-chk.sh
      - run: scripts/buildtable.pl >/tmp/table.mediawiki || exit 1
      - run: scripts/diffcheck.sh
